<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_layout/Admin.Master" AutoEventWireup="true" CodeBehind="Manageproduct.aspx.cs" Inherits="MobileHub.Admin_layout.Manageproduct" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-10">
                        <h2>Manage Product</h2>
                    </div>
                    <div class="col-sm-2">
                        <a href="AddProduct.aspx" class="btn btn-success"><i class="fa fa-plus-circle fa-fw"></i>Add new product</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.content-header -->
        <!-- Main content -->
        <div class="clearfix"></div>
        <section class="content">
            <div class="container">

                <div class="row">
                    <div class="table-responsive">
                        <asp:GridView ID="GridView1" runat="server" class="table table-striped mytable" AutoGenerateColumns="false" AllowPaging="True"
                            OnRowCancelingEdit="GridView1_RowCancelingEdit" DataKeyNames="PID" CellPadding="4"
                            OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" ForeColor="#333333">

                            <Columns>

                                <asp:TemplateField HeaderStyle-Width="150px">

                                    <ItemTemplate>

                                        <asp:LinkButton ID="LkB1" runat="server" CommandName="Edit">Edit</asp:LinkButton>

                                    </ItemTemplate>

                                    <EditItemTemplate>

                                        <asp:LinkButton ID="LkB2" runat="server" CommandName="Update">Update</asp:LinkButton>

                                        <asp:LinkButton ID="LkB3" runat="server" CommandName="Cancel">Cancel</asp:LinkButton>

                                    </EditItemTemplate>

                                </asp:TemplateField>



                                <asp:TemplateField HeaderText="Name" HeaderStyle-Width="200px">



                                    <ItemTemplate>

                                        <asp:Label ID="name" runat="server" Text='<%# Eval("PName" ) %>'></asp:Label>

                                    </ItemTemplate>

                                    <EditItemTemplate>

                                        <asp:TextBox ID="txt_Name" runat="server" Text='<%# Eval("PName" ) %>'></asp:TextBox>

                                    </EditItemTemplate>

                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Category ID" HeaderStyle-Width="200px">

                                    <ItemTemplate>

                                        <asp:Label ID="cat_id" runat="server" Text='<%# Eval("Cat_id" ) %>'></asp:Label>

                                    </ItemTemplate>

                                    <EditItemTemplate>

                                        <asp:TextBox ID="Cat_id" runat="server" Text='<%# Eval("Cat_id" ) %>'></asp:TextBox>

                                    </EditItemTemplate>

                                </asp:TemplateField>



                                <asp:TemplateField HeaderText="Image" HeaderStyle-Width="200px">

                                    <ItemTemplate>

                                        <asp:Image ID="Image1" runat="server" ImageUrl='<%#"~/Productimg/"+Eval("Pimage") %>'
                                            Height="80px" Width="100px" />

                                    </ItemTemplate>

                                    <EditItemTemplate>

                                        <asp:Image ID="img_user" runat="server" ImageUrl='<%#"~/Productimg/"+Eval("Pimage" ) %>'
                                            Height="80px" Width="100px" /><br />

                                        <asp:FileUpload ID="FileUpload1" runat="server" />

                                    </EditItemTemplate>

                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Description" HeaderStyle-Width="200px">

                                    <ItemTemplate>

                                        <asp:Label ID="description" runat="server" Text='<%# Eval("Description" ) %>'></asp:Label>

                                    </ItemTemplate>

                                    <EditItemTemplate>

                                        <asp:TextBox ID="description" runat="server" Text='<%# Eval("Description" ) %>'></asp:TextBox>

                                    </EditItemTemplate>

                                </asp:TemplateField>

                                <asp:TemplateField HeaderText="Price" HeaderStyle-Width="200px">

                                    <ItemTemplate>

                                        <asp:Label ID="price" runat="server" Text='<%# Eval("Price" ) %>'></asp:Label>

                                    </ItemTemplate>

                                    <EditItemTemplate>

                                        <asp:TextBox ID="price" runat="server" Text='<%# Eval("Price" ) %>'></asp:TextBox>

                                    </EditItemTemplate>

                                </asp:TemplateField>

                            </Columns>

                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />

                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />

                        </asp:GridView>
                    </div>
                </div>
            </div>
        </section>
        <!-- /maincontent -->
    </div>
    <!-- /.content-wrapper -->
</asp:Content>

